---
title: "Vector and Matrices"
chapter: "18.02 - Multivariable calculus"
author: "TgX.2"
format:
  html:
    toc: true
    toc-depth: 3
    toc-title: "Mục lục bài viết"
    toc-location: right
    css: ../styles.css
    include-in-header:
      text: | 
        <script src="../navigation.js" defer></script>
---



___
# Lời bạt 
Thật ra lời bạt là lời nói ở cuối sách cơ, nhưng mà thôi, chấp nhận đi.

Vector trong những lời tôi nói, ví dụ, và viết, suy nghĩ trong đầu bạn, ở chương **18.02** nên là vector trong mặt phẳng (2D), hoặc trong không gian 3 chiều (3D).

Các tính chất hầu như (tất cả) đều giống nhau ở đa chiều khác nhau, nhưng sẽ dễ dàng và để chương **18.06** không bị mất đi tinh thần của nó. Các ví dụ trong chương này nên là 2d và 3d cho dễ hiểu.


___
# Vectors
Vector thì không có gì đáng để chú tâm cả, bởi vì nó được giảng dạy khá nhiều trong môn hình học ở cấp 3, và có thể coi là cốt lõi của hình học cấp 3.

Về vector thì có hai thứ để cấu tạo nên nó:

* $dir(\vec A)$ : direction 
* $|\vec A|$ : magnitude / length

Một vector cơ bản giới thiệu trong không gian ba chiều sau:

$$
\vec A = a_1 \hat i + a_2 \hat j + a_3 \hat k = <a_1, a_2, a_3>
$$

Một vector cũng có thể biểu diễn bằng hai điểm, ví dụ như là hai điểm P và Q thì vector $\vec{PQ}$ sẽ có đầu là điểm P và kết thúc ở điểm Q.

## Độ dài của vector

Ở cấp 3 chúng ta đã được học, nó chính là 

$$
\vec A <a_1, a_2, a_3> = \sqrt{\left(a_1^2 + a_2^2 + a_3^2 \right)}
$$

## Cộng vector và nhân vector với scalar

Quá dễ, không bàn tới

##

:::{.callout-warning}
## Lưu ý 
Lưu ý rằng, các vector có cùng hướng và cùng độ dài là giống nhau, không quan trọng điểm đặt của nó.
Điều này tớ cho rằng nó sẽ dễ dàng hơn trong việc truyền đạt phép cộng và nhân vector với một số sau này.
:::
___
# Dot product

Như ở cấp 3 ta đã học. Tổng quát hóa nó lên, tích vô hướng hai vector là:

$$
\vec A \cdot \vec B = \sum{a_i b_i}
$$

Và một cách khác theo hình học là:

$$
\vec A \cdot \vec B = |\vec A| \cdot |\vec B| \cdot \cos(\theta)
$$

:::{.callout-tip}
## Chứng minh


:::

## Applications

Ứng dụng của dot product: 

* 1. Tính độ dài và góc (đặc biệt là góc)
* 2. Xác định tính trực giao

___
# Determinants

Định thức, như ở cấp 3 chúng ta đã được học định thức bậc nhất:

$$
\begin{vmatrix}
a_1 & a_2 \\ 
b_1 & b_2
\end{vmatrix} = a_1b_2 - a_2b_1
$$

Và bây giờ tớ sẽ giới thiệu tới định thức $3 \times 3$

$$
\begin{vmatrix}
a_1 & a_2 & a_3 \\ 
b_1 & b_2 & b_3 \\ 
c_1 & c_2 & c_3
\end{vmatrix} 
= a_1 \begin{vmatrix}
b_2 & b_3 \\ 
c_2 & c_3 
\end{vmatrix}
- a_2 \begin{vmatrix}
b_1 & b_3 \\ 
c_1 & c_3 
\end{vmatrix}
+ a_3 \begin{vmatrix}
b_1 & b_2 \\ 
c_1 & c_2 s
\end{vmatrix}
$$

Còn $\det(A_{n \times n})$ thì sẽ được giới thiệu ở **18.06**

Một ứng dụng của định thức là diện tích tam giác tạo bởi hai vector $\vec A$ và $\vec B$.



___
# Cross product


___
# Matrices

Ma trận là gì? Có lẽ sẽ được nói rõ hơn trong **18.06** nhưng bây giờ chúng ta sẽ hiểu nó đơn giản là một tập hợp các số nén trong một bảng $n \times m$ n,m tùy ý.

Thường thì các đại lượng có liên hệ với nhau qua biến đổi tuyến tính; Ví dụ như là việc thay đổi hệ tọa độ, không phải là $\hat i = <1, 0, 0>$, $\hat j = <0, 1, 0>$, $\hat k = <0, 0, 1>$ nữa, mà sẽ là 3 vector tùy ý làm gốc tọa độ, vậy thì vector gốc ban đầu $\vec V$ sẽ ở đâu sau khi biến đổi tuyến tính.

For example:

$$
\begin{cases}
u_1 = 2x_1 + 3x_2 + 3x_3 \\ 
u_2 = 2x_1 + 4x_2 + 5x_3 \\ 
u_3 = x_1 + x_2 + 2x_3
\end{cases}
$$

Khi viết dưới dạng nhân ma trận, sẽ là:

$$
\begin{bmatrix}
2 & 3 & 3 \\ 
2 & 4 & 5 \\ 
1 & 1 & 2  
\end{bmatrix}
\begin{bmatrix}
x_1 \\ 
x_2 \\ 
x_3
\end{bmatrix}
=
\begin{bmatrix}
u_1 \\ 
u_2 \\ 
u_3 
\end{bmatrix}
$$

i.e. $AX = U$

Việc nhân ma trận như thế nào, không cần bàn cãi gì nữa, nó là công việc của **18.06**, nhưng nếu bạn là học sinh chuyên tin thì sẽ biết nó hoạt động như thế nào.

Đơn giản mà nói, nó sẽ là tích vô hướng giữa các hàng $i$ ma trận A và các cột $j$ của X, nó sẽ cho ra giá trị $a_{ij}$ của ma trận U.

:::{.callout-warning collapse="true"}
## Lưu ý
Chính vì thế nên chiều dài của A phải bằng chiều cao của X.
:::

## Identity matrix

Ma trận đơn vị là ma trận có số 1 ở đường chéo chính và tất cả số 0 ở các vị trí còn lại, ví dụ:

$$
I_{3 \times 3} = \begin{bmatrix}
1 & 0 & 0 \\ 
0 & 1 & 0 \\ 
0 & 0 & 1
\end{bmatrix}
$$

và 

$$
IX = X 
$$

vì ma trận này không làm gì cả, đối chiếu với biến đổi tuyến tính, thì nó chính là không làm gì cả. Vì ma trận đơn vị này chính là hợp lại của các vector basis. ;)

## Inverse matrix

Ta thường giải $Ax = B \Rightarrow x = \frac B A = A^{-1}B$. Vậy chúng ta có thể áp dụng nó trong ma trận được không?

Được👍🏿.

Vậy chúng ta tính 

___
# Square systems; Equation of planes


___
# Parametric equations for lines and curves 


___
# Velocity, Acceleration


___
# Kepler's second law
