---
title: "Triple integrals and Surface integrals in 3D space"
chapter: "18.02 - Multivariable calculus"
author: "TgX.2"
format:
  html:
    toc: true
    toc-depth: 3
    toc-title: "Mục lục bài viết"
    toc-location: right
    css: ../styles.css
    include-in-header:
      text: | 
        <script src="../navigation.js" defer></script>
---

___
# Triple integrals

Tương tự như trong tích phân kép, tích phân bội ba có dạng:

$$
\iiint f(x, y, z) \mathbf dV
$$

Nhớ rằng, $\mathbf dV$ có thể là $\mathbf dx \mathbf dy \mathbf dz$ hoặc là $r \mathbf dr\mathbf d\theta\mathbf dz$, ...


**Ví dụ:**

Tìm thể tích phần giới hạn bởi 2 paraboloid:

$$
z = x^2 + y^2 \tag{1}
$$

$$
z = 4 - x^2 - y^2 \tag{2}
$$


```{python}
#| echo: true
#| code-fold: true
#| warning: false
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-np.sqrt(2), np.sqrt(2), 300)
y = np.linspace(-np.sqrt(2), np.sqrt(2), 300)

X, Y = np.meshgrid(x, y)
R2 = X**2 + Y**2

Z1 = R2                 
Z2 = 4 - R2              
mask = R2 <= 2

Z1 = np.where(mask, Z1, np.nan)
Z2 = np.where(mask, Z2, np.nan)

fig = plt.figure(figsize=(6, 6))
ax = fig.add_subplot(111, projection="3d")

ax.plot_surface(
    X, Y, Z1,
    cmap="viridis",
    alpha=0.72,
    linewidth=0,
    antialiased=True
)

ax.plot_surface(
    X, Y, Z2,
    cmap="magma",
    alpha=0.72,
    linewidth=0,
    antialiased=True
)

theta = np.linspace(0, 2*np.pi, 500)

r = np.sqrt(2)

xc = r * np.cos(theta)
yc = r * np.sin(theta)
zc = np.full_like(theta, 2)

ax.plot(
    xc, yc, zc,
    color="black",
    linewidth=3
)

ax.set_xlabel(r"$x$", fontsize=13)
ax.set_ylabel(r"$y$", fontsize=13)
ax.set_zlabel(r"$z$", fontsize=13)

ax.set_xlim(-1.6, 1.6)
ax.set_ylim(-1.6, 1.6)
ax.set_zlim(0, 4)

ax.view_init(elev=28, azim=45)

ax.legend()

plt.tight_layout()
plt.show()
```

Ta sẽ tích phân $\mathbf dz$ trước.

:::{.callout-tip collapse="true"}
## Suy nghĩ tại sao lại là dz trước
Bởi vì từ hai điểm x và y, ta có thể dễ dàng xác định được biên của z khi tích phân, đó là hai hàm.
:::

Bây giờ phương trình trở thành:

$$
\int_?^?\int_?^?\int_{x^2 + y^2}^{4 - x^2 - y^2} 1\mathbf dz \mathbf dy \mathbf dx
$$

Việc tính biên của x và y, ta có thể thấy rằng nó chính là một hình tròn trên mặt phẳng Oxy. Nhưng mà đó chỉ là nhìn hình ta biết, vì vậy chúng ta phải lập luận bằng toán học:

$$
z_{bottom} < z_{top} \\ 
\Rightarrow x^2 + y^2 < 4 - x^2 - y^2 \\ 
\Rightarrow x^2 + y^2 < 2
$$

Chính xác là nó chính là hình tròn với bán kính là $\sqrt2$.

```{python}
#| echo: true
#| code-fold: true
#| warning: false
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-np.sqrt(2), np.sqrt(2), 250)
y = np.linspace(-np.sqrt(2), np.sqrt(2), 250)
X, Y = np.meshgrid(x, y)

R2 = X**2 + Y**2
mask = R2 <= 2

Z1 = np.where(mask, R2, np.nan)
Z2 = np.where(mask, 4 - R2, np.nan)

fig = plt.figure(figsize=(6, 6))
ax = fig.add_subplot(111, projection="3d")

ax.plot_surface(
    X, Y, Z1,
    cmap="viridis",
    alpha=0.7,
    linewidth=0,
    antialiased=True
)

ax.plot_surface(
    X, Y, Z2,
    cmap="magma",
    alpha=0.7,
    linewidth=0,
    antialiased=True
)

theta = np.linspace(0, 2*np.pi, 500)
r = np.sqrt(2)

xc = r * np.cos(theta)
yc = r * np.sin(theta)
zc = np.full_like(theta, 2)

ax.plot(
    xc, yc, zc,
    color="black",
    linewidth=3
)

ax.plot(
    xc, yc, np.zeros_like(theta),
    color="black",
    linewidth=1.5,
    alpha=0.5
)

ax.plot_trisurf(
    xc, yc, np.zeros_like(theta),
    color="gray",
    alpha=0.18,
    linewidth=0
)

ax.set_xlabel(r"$x$", fontsize=13)
ax.set_ylabel(r"$y$", fontsize=13)
ax.set_zlabel(r"$z$", fontsize=13)

ax.set_xlim(-1.7, 1.7)
ax.set_ylim(-1.7, 1.7)
ax.set_zlim(0, 4)

ax.view_init(elev=28, azim=45)

plt.tight_layout()
plt.show()
```

Vì vậy ta có thể khiến y phụ thuộc vào x. Bằng phương trình đường tròn.

```{python}
#| echo: true
#| code-fold: true
#| warning: false
import numpy as np
import matplotlib.pyplot as plt

y = np.linspace(-2, 2, 500)

z1 = y**2
z2 = 4 - y**2

a = np.sqrt(2)
y0 = 0.75

z_bottom = y0**2
z_top = 4 - y0**2

fig, ax = plt.subplots(figsize=(6, 6))

ax.plot(y, z1, color=plt.cm.viridis(0.5), linewidth=1.5)
ax.plot(y, z2, color=plt.cm.magma(0.5), linewidth=1.5)

ax.scatter([-a, a], [2, 2], color="black", s=45, zorder=3)

ax.plot([-a, -a], [0, 2], "--", color="black", linewidth=1)
ax.plot([a, a], [0, 2], "--", color="black", linewidth=1)

ax.scatter(y0, 0, color="black", s=45, zorder=6)

ax.plot([y0, y0], [0, z_bottom], "--", color="black", linewidth=1.3)
ax.plot([y0, y0], [z_bottom, z_top], color="black", linewidth=4)
ax.plot([y0, y0], [z_top, 0], "--", color="black", linewidth=1.3)

ax.axhline(0, color="black", linewidth=1.8)
ax.axvline(0, color="black", linewidth=1.8)

ax.annotate(
    "",
    xy=(2.15, 0),
    xytext=(2.0, 0),
    arrowprops=dict(arrowstyle="->", color="black", linewidth=1.8)
)

ax.annotate(
    "",
    xy=(0, 4.35),
    xytext=(0, 4.15),
    arrowprops=dict(arrowstyle="->", color="black", linewidth=1.8)
)

ax.text(2.18, -0.12, r"$y$", fontsize=18)
ax.text(0.08, 4.28, r"$z$", fontsize=18)

ax.text(-a, -0.22, r"$-\sqrt{2}$", ha="center", fontsize=15)
ax.text(a, -0.22, r"$\sqrt{2}$", ha="center", fontsize=15)
ax.text(-0.15, 2.05, r"$2$", ha="right", fontsize=14)
ax.text(y0, -0.22, r"$y_0$", ha="center", fontsize=15)

ax.set_xlim(-2.15, 2.15)
ax.set_ylim(-0.35, 4.45)
ax.set_aspect("equal", adjustable="box")
ax.set_xticks([])
ax.set_yticks([])

for spine in ax.spines.values():
    spine.set_visible(False)

plt.tight_layout()
plt.show()
```

Vậy cuối cùng phương trình trở thành:

$$
\int_{-\sqrt2}^{\sqrt2}\int_{-\sqrt{2-x^2}}^{\sqrt{2 - x^2}}\int_{x^2 + y^2}^{4 - x^2 - y^2} 1 \mathbf dz \mathbf dy \mathbf dx
$$

Nhưng mà nó khá là khó và rất rối để ngồi nguyên hàm rồi tính.

___
# Cylindrical coordinates

Vì thế chúng ta đã có tọa độ trụ.

Nó chính là bản nâng cấp của tọa độ cực, vì thế:

$$
x = r\cos\theta \qquad y = r\sin\theta \qquad z = z
$$

Với r là khoảng cách đến z, $\theta$ là khoảng góc từ mặt phẳng xz.

Tọa độ trục chính xác là tọa độ cực nhưng thêm trục cao.

Hàm bây giờ trở thành:

$$
\int_0^{2\pi}\int_0^{\sqrt2}\int_{x^2 + y^2}^{4 - x^2 - y^2}1\mathbf dz r\mathbf dr\mathbf d\theta
$$

___
# Spherical coordinates

Tọa độ cầu.

Để miêu tả một điểm trong không gian, hiện tại chúng ta đã có 3 cách:

- **3D:** $(x, y, z)$
- **Cylindrical coordinates:** $(r, \theta, z)$
- **Spherical coordinates:** $(\rho, \phi, \theta)$
 
Trong tọa độ cầu, các tham số biểu diễn:

- $\rho$: Khoảng cách từ điểm đến gốc tọa độ.
- $\phi$: Khoảng cách với trục z ($0 \leq \phi \leq \pi$).
- $\theta$: Khoảng cách với mặt phẳng xz ($0 \leq \theta \leq 2\pi$).

```{python}
#| echo: true
#| code-fold: true
#| warning: false
import numpy as np
import matplotlib.pyplot as plt

rho = 1.2
phi = np.deg2rad(45)     
theta = np.deg2rad(35)    

x = rho*np.sin(phi)*np.cos(theta)
y = rho*np.sin(phi)*np.sin(theta)
z = rho*np.cos(phi)

fig = plt.figure(figsize=(6,6))
ax = fig.add_subplot(111, projection='3d')

L = 1.5

ax.quiver(0,0,0,L,0,0,color='black',arrow_length_ratio=0.05)
ax.quiver(0,0,0,0,L,0,color='black',arrow_length_ratio=0.05)
ax.quiver(0,0,0,0,0,L,color='black',arrow_length_ratio=0.05)

ax.text(L+0.05,0,0,'x',fontsize=13)
ax.text(0,L+0.05,0,'y',fontsize=13)
ax.text(0,0,L+0.05,'z',fontsize=13)
ax.text(0,0,0,'O',fontsize=12)

ax.scatter(x,y,z,s=40,color='crimson')
ax.text(x+0.03,y+0.03,z+0.03,r'$A$',fontsize=13)

ax.plot([0,x],[0,y],[0,z],
        color='crimson',
        linewidth=2)

# rho label
ax.text(x*0.45,y*0.45,z*0.45,r'$\rho$',fontsize=13)

r = rho*np.sin(phi)

ax.plot([0,x],[0,y],[0,0],
        '--',color='gray',linewidth=1)

ax.plot([x,x],[y,y],[0,z],
        '--',color='gray',linewidth=1)

u = np.linspace(0,1,2)
v = np.linspace(0,L,2)

U,V = np.meshgrid(u,v)

X = U*x
Y = U*y
Z = V

ax.plot_surface(
    X,Y,Z,
    color='steelblue',
    alpha=0.20,
    linewidth=0,
    shade=False
)

R1 = 0.35

t = np.linspace(0,theta,120)

ax.plot(
    R1*np.cos(t),
    R1*np.sin(t),
    np.zeros_like(t),
    color='green',
    linewidth=2
)

mid = theta/2

ax.text(
    1.12*R1*np.cos(mid),
    1.12*R1*np.sin(mid),
    0,
    r'$\theta$',
    fontsize=13
)

R2 = 0.45

p = np.linspace(0,phi,120)

xx = R2*np.sin(p)*np.cos(theta)
yy = R2*np.sin(p)*np.sin(theta)
zz = R2*np.cos(p)

ax.plot(xx,yy,zz,
        color='purple',
        linewidth=2)

m = len(xx)//2

ax.text(
    xx[m]+0.02,
    yy[m]+0.02,
    zz[m],
    r'$\phi$',
    fontsize=13
)

ax.set_xlim(-0.2,1.4)
ax.set_ylim(-0.2,1.2)
ax.set_zlim(0,1.4)

ax.set_box_aspect([1,1,1])

ax.set_xticks([])
ax.set_yticks([])
ax.set_zticks([])

ax.grid(False)

ax.xaxis.pane.fill=False
ax.yaxis.pane.fill=False
ax.zaxis.pane.fill=False

plt.tight_layout()
plt.show()
```

Công thức:

$$
x = \rho\sin\phi\cos\theta \\ 
y = \rho\sin\phi\sin\theta \\ 
z = \rho\cos\phi
$$

và 

$$
\rho = \sqrt{x ^2 + y^2 + z^2} = \sqrt{r^2 + z^2}
$$

## Tích phân bội ba trong tọa độ cầu

$$
\mathbf dV = \rho^2\sin\phi \mathbf d\rho \mathbf d\phi\mathbf d\theta 
$$

:::{.callout-note collapse="true"}
## The Jacobians

Ta có:

$$
x = \rho\sin\phi\cos\theta \qquad y = \rho\sin\phi\sin\theta \qquad z = \rho\cos\phi
$$

$$
J = \frac{\partial(x, y, z)}{\partial(\rho, \phi, \theta)} = \begin{vmatrix}
x_\rho & x_\phi & x_\theta \\ 
y_\rho & y_\phi & y_\theta \\ 
z_\rho & z_\phi & z_\theta 
\end{vmatrix}
$$

$$
J = x_\rho\begin{vmatrix} 
y_\phi & y_\theta \\ 
z_\phi & z_\theta 
\end{vmatrix} - x_\phi\begin{vmatrix}
y_\rho & y_\theta \\ 
z_\rho & z_\theta 
\end{vmatrix} + x_\theta\begin{vmatrix}
y_\rho & y_\phi \\ 
z_\rho & z_\phi 
\end{vmatrix}
$$

$$
x_\rho = \sin\phi\cos\theta \qquad 
x_\phi = \rho\cos\phi\cos\theta \qquad 
x_\theta = -\rho\sin\phi\sin\theta \\ 
y_\rho = \sin\phi\sin\theta \qquad 
y_\phi = \rho\cos\phi\sin\theta \qquad 
y_\theta = \rho\sin\phi\cos\theta \\ 
z_\rho = \cos\phi \qquad 
z_\phi = -\rho\sin\phi \qquad
z_\theta = 0
$$

$$
\begin{vmatrix}
y_\phi & y_\theta \\ 
z_\phi & z_\theta 
\end{vmatrix} = \rho^2\sin\phi^2\cos\theta
$$

$$
\begin{vmatrix}
y_\rho & y_\theta \\ 
z_\rho & z_\theta 
\end{vmatrix} = -\rho\sin\phi\cos\phi\cos\theta
$$

$$
\begin{vmatrix}
y_\rho & y_\phi \\ 
z_\rho & z_\phi 
\end{vmatrix} = -\rho\sin\theta
$$

$$
\Rightarrow J = \rho^2\sin\phi^3\cos\theta^2 + \rho^2\sin\phi\cos\phi^2\cos\theta^2 + \rho^2\sin\theta^2\sin\phi 
$$

$$
\Rightarrow J = \rho^2\sin\phi(\sin\phi^2\cos\theta^2 + \cos\phi^2\cos\theta^2 + \sin\theta^2)
$$

$$
\Rightarrow J = \rho^2\sin\phi
$$

Cuối cùng: $\mathbf dx\mathbf dy \mathbf dz = \rho^2\sin\phi \mathbf d\rho\mathbf d\phi \mathbf d\theta$
:::

**Ví dụ:** Tính thể tích phần chóp được tạo bởi một hình cầu $\rho = 1$ và cắt ngang bởi mặt phẳng $z = \frac 1 {\sqrt2}$.

```{python}
#| echo: true
#| code-fold: true
#| warning: false
import numpy as np
import matplotlib.pyplot as plt

R = 1.0
z0 = 1 / np.sqrt(2)

fig = plt.figure(figsize=(6, 6))
ax = fig.add_subplot(111, projection='3d')


u = np.linspace(0, 2*np.pi, 200)
v = np.linspace(0, np.pi, 150)

U, V = np.meshgrid(u, v)

X = R * np.cos(U) * np.sin(V)
Y = R * np.sin(U) * np.sin(V)
Z = R * np.cos(V)


Xu = np.ma.masked_where(Z < z0, X)
Yu = np.ma.masked_where(Z < z0, Y)
Zu = np.ma.masked_where(Z < z0, Z)

ax.plot_surface(
    Xu, Yu, Zu,
    cmap='plasma',
    rcount=180,
    ccount=180,
    linewidth=0,
    antialiased=True,
    shade=True,
    alpha=1
)

Xl = np.ma.masked_where(Z > z0, X)
Yl = np.ma.masked_where(Z > z0, Y)
Zl = np.ma.masked_where(Z > z0, Z)

ax.plot_surface(
    Xl, Yl, Zl,
    cmap='viridis',
    rcount=180,
    ccount=180,
    linewidth=0,
    antialiased=True,
    shade=True,
    alpha=0.5
)

r = np.sqrt(R**2 - z0**2)

x = np.linspace(-r, r, 200)
y = np.linspace(-r, r, 200)

Xp, Yp = np.meshgrid(x, y)

mask = Xp**2 + Yp**2 <= r**2

Xp = np.ma.masked_where(~mask, Xp)
Yp = np.ma.masked_where(~mask, Yp)
Zp = np.ma.masked_where(~mask, np.full_like(Xp, z0))

ax.plot_surface(
    Xp, Yp, Zp,
    color='white',
    alpha=0.70,
    linewidth=0,
    shade=False
)

t = np.linspace(0, 2*np.pi, 500)

xc = r * np.cos(t)
yc = r * np.sin(t)
zc = np.full_like(t, z0)

ax.plot(
    xc, yc, zc,
    color='black',
    linewidth=3
)

lim = 1.05

ax.set_xlim(-lim, lim)
ax.set_ylim(-lim, lim)
ax.set_zlim(-lim, lim)


ax.set_box_aspect((1, 1, 1))

ax.view_init(elev=28, azim=45)

ax.set_xlabel(r'$x$', fontsize=16)
ax.set_ylabel(r'$y$', fontsize=16)
ax.set_zlabel(r'$z$', fontsize=16)

ax.grid(True)

plt.tight_layout()
plt.show()
```

$$
\int_0^{2\pi}\int_0^{\pi/4}\int_{\frac 1 {\sqrt2\cos\phi}}^1\rho^2\sin\phi\mathbf d\rho\mathbf d\phi\mathbf d\theta
$$

Tự tính.

$$
\frac {2\pi} 3 - \frac {5\pi}{6\sqrt2}
$$

___
# Application to gravitation

:::{.callout-important}
## tl;dr
Phần này là đọc thêm (Không phải là do tôi hiểu gì cả nên không biết viết gì cả.
:::

Gravitational force exerted on mass m at origin by a mass $\Delta M$ at $(x, y, z)$ is given by $|\vec F| = \frac{G\Delta M m}{\rho^2}$, $dir(\vec F) = \frac{<x, y, z>} \rho$, i.e. $\vec F = \frac{G \Delta M m}{\rho^3}$. (G = gravitational constant).

If instead of a point mass we have a solid with density $\delsity$


---
# Vector fields in space

Giống như trong mặt phẳng, trường vector trong không gian là chỉ việc ở tại mọi điểm đều có một vector phụ thuộc vào $(x, y, z)$.

$$
\vec F = <P, Q, R>
$$

**Ví dụ:** 

- Trường lực hấp dẫn giữa một vật ở góc tọa độ có khối lượng M và một điểm ở $(x, y, z)$.

Trường $\vec F$ hướng thẳng về gốc tọa độ, và độ lớn tỉ lệ thuận $\frac c {\rho^2}$

$$
\vec F = -c \frac{<x, y, z>}{\rho^3}
$$

- Trường điện từ và trường từ trường.

- Trường vận tốc.

- Trường Gradient, $u = u(x, y, z) \qquad \nabla u = <u_x, u_y, u_z>$

___
# Flux 3D

Như trong mặt phẳng, ta có:

$$
\int_C \vec F \cdot \hat{\mathbf n} \mathbf ds
$$

mô tả thông lượng thông qua một đường cong trong một trường vector $\vec F$.

Và bây giờ chúng ta đang làm việc trong không gian vì vậy chúng ta không thể tính được bao nhiêu gió đi qua một đường cong, mà phải là qua một mặt phẳng. Vì vậy chúng ta không thể dùng tích phân đường nữa mà phải sử dụng tích phân mặt.

Với trường vector $\vec F$, mặt phẳng S, vector pháp tuyến $\hat{\mathbf n}$, FLux:

$$
\iint \vec F \cdot \hat{\mathbf n}\mathbf dS
$$

Notation: $\mathbf d\vec S = \hat{\mathbf n}\mathbf dS$.

:::{.callout-caution}
## Chú ý

- Chiều của $\hat{\mathbf n}$: Không có một quy ước chuẩn nào cho chiều của vector pháp tuyến. Việc lựa chọn như thế nào ảnh hướng khá nhiều đến kết quả cuối cùng. Nó cũng giống với Flux trong 2D, việc vector đâm vào cùng hướng hay ngược hướng với vector pháp tuyến sẽ quyết định đến dấu.

- Không có một công thức đẹp giống như trong 2D, $\int_C M\mathbf dx + N\mathbf dy$ là điều không có trong không gian.
:::

**Ví dụ 1:** Cho trường vector $\vec F = <x ,y, z>$, và một hình cầu tâm ở gốc tọa độ và bán kính a.

$$
\hat{\mathbf n} = \frac 1 a <x, y, z> (\text{other choice: } -\frac 1 a <x, y, z>)
$$

$$
\iint_S \vec F \cdot \hat{\mathbf n}\mathbf dS = \iint_S a \mathbf dS = 4\pi a^3
$$

## Một số kiểu tham số hóa

0) Mặt phẳng $z = a$ song song với mặt phẳng xy: 
$$
\hat{\mathbf n} = \pm \hat{\mathbf k} \qquad \mathbf dS = \mathbf dx \mathbf dy
$$

1) Hình cầu bán kính a, tâm tại gốc tọa độ, dùng $\phi, \theta$:
$$
\hat{\mathbf n} = \frac 1 a <x, y, z> \qquad \mathbf dS = a^2\sin\phi\mathbf d\phi\mathbf d\theta 
$$

2) Hình trụ bán kính a, tâm ở trục z, dùng $z, \theta$:
$$
\hat{\mathbf n} = \frac 1 a <x, y, 0> \qquad \mathbf dS = a\mathbf dz\mathbf d\theta 
$$

3) Hình phụ thuộc vào x và y, $z = f(x, y)$, dùng $x, y$:
$$
\hat{\mathbf n}\mathbf dS = <-f_x, -f_y, 1>\mathbf dx\mathbf dy
$$

___
# Flux through a graph

**Cách tính $dS$:** của một mặt được viết dưới dạng đồ thị:
$$
z = f(x, y)
$$

```{python}
#| echo: true
#| code-fold: true
#| warning: false
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

def f(x, y):
    return 0.25*x**2 + 0.15*y**2 + 0.10*x*y

x = np.linspace(-0.8, 1.8, 60)
y = np.linspace(-0.8, 1.8, 60)
X, Y = np.meshgrid(x, y)
Z = f(X, Y)

x0 = 0.4
y0 = 0.3
dx = 0.55
dy = 0.45

B1 = np.array([x0, y0, 0])
B2 = np.array([x0+dx, y0, 0])
B3 = np.array([x0+dx, y0+dy, 0])
B4 = np.array([x0, y0+dy, 0])

P1 = np.array([x0, y0, f(x0,y0)])
P2 = np.array([x0+dx, y0, f(x0+dx,y0)])
P3 = np.array([x0, y0+dy, f(x0,y0+dy)])
P4 = np.array([x0+dx, y0+dy, f(x0+dx,y0+dy)])

u = P2-P1
v = P3-P1

# Normal
n = np.cross(u,v)
n = n/np.linalg.norm(n)*0.35

fig = plt.figure(figsize=(6,7))
ax = fig.add_subplot(111, projection='3d')

ax.plot_surface(
    X, Y, Z,
    cmap='viridis',
    alpha=0.3,
    edgecolor='0.5',
    linewidth=0.3,
    antialiased=True
)

bottom = np.vstack([B1,B2,B3,B4,B1])
ax.plot(
    bottom[:,0],
    bottom[:,1],
    bottom[:,2],
    color='black',
    linewidth=2
)

for b,p in zip([B1,B2,B3,B4],[P1,P2,P4,P3]):
    ax.plot(
        [b[0],p[0]],
        [b[1],p[1]],
        [b[2],p[2]],
        '--',
        color='0.6',
        linewidth=1
    )

poly = Poly3DCollection(
    [[P1,P2,P4,P3]],
    facecolor='royalblue',
    alpha=0.45,
    edgecolor='navy',
    linewidth=2
)
ax.add_collection3d(poly)

ax.scatter(
    [P1[0],P2[0],P3[0],P4[0]],
    [P1[1],P2[1],P3[1],P4[1]],
    [P1[2],P2[2],P3[2],P4[2]],
    color='k',
    s=30
)

ax.quiver(
    *P1,
    *u,
    color='crimson',
    linewidth=2.5,
    arrow_length_ratio=0.12
)

ax.quiver(
    *P1,
    *v,
    color='forestgreen',
    linewidth=2.5,
    arrow_length_ratio=0.12
)

ax.quiver(
    *P1,
    *n,
    color='purple',
    linewidth=2.5,
    arrow_length_ratio=0.18
)

ax.text(*(P1+[-0.08,-0.08,0.05]), r"$P$", fontsize=13)
ax.text(*(P2+[0.02,-0.05,0.04]), r"$P_x$", fontsize=13)
ax.text(*(P3+[-0.08,0.02,0.04]), r"$P_y$", fontsize=13)
ax.text(*(P4+[0.02,0.02,0.04]), r"$P_{xy}$", fontsize=13)

ax.text(
    (B1[0]+B2[0])/2,
    B1[1]-0.08,
    0,
    r"$dx$",
    fontsize=13
)

ax.text(
    B4[0]-0.08,
    (B1[1]+B4[1])/2,
    0,
    r"$dy$",
    fontsize=13
)

ax.text(*(P1+0.55*u), r"$\mathbf{u}$", fontsize=14, color='crimson')
ax.text(*(P1+0.55*v), r"$\mathbf{v}$", fontsize=14, color='forestgreen')
ax.text(*(P1+1.05*n), r"$\mathbf{u}\times\mathbf{v}$",
        fontsize=13, color='purple')

ax.set_xlabel("$x$", fontsize=12)
ax.set_ylabel("$y$", fontsize=12)
ax.set_zlabel("$z$", fontsize=12)

ax.set_xlim(-0.2,1.5)
ax.set_ylim(-0.2,1.4)
ax.set_zlim(0,1.2)

ax.set_box_aspect([1,1,0.8])

ax.view_init(elev=32, azim=-122)

ax.grid(False)

plt.tight_layout()
plt.show()
```

$$
\Delta \vec S = \vec u \times \vec v
$$

Mà ta có:

$$
\vec u = <\Delta x, 0, f_x\Delta x> = \Delta x <1, 0, f_x>
$$

vì $f(x + \Delta x, y) \approx f(x, y) + f_x\Delta x$

Tương tự với $\vec v$, ta có:

$$
\vec v = \Delta y<0, 1, f_y>
$$

$$
\Delta \vec S = \vec u \times \vec v = \Delta x <1, 0, f_x>\times \Delta y<0, 1, f_y>
$$

Tính Cross product:

$$
\begin{vmatrix}
\hat i & \hat j & \hat k \\
1 & 0 & f_x \\  
0 & 1 & f_y 
\end{vmatrix} = 
\hat i \begin{vmatrix}
0 & f_x \\ 
1 & f_y
\end{vmatrix} - 
\hat j \begin{vmatrix}
1 & f_x \\ 
0 & f_y
\end{vmatrix} +
\hat k \begin{vmatrix}
1 & 0 \\ 
0 & 1
\end{vmatrix}
$$
$$
\Rightarrow -f_x \hat i - f_y \hat j + \hat k
$$

Cuối cùng:

$$
\Delta \vec S = \pm<-f_x,-f_y,1>\Delta x \Delta y
$$

hay

$$
d\vec S = \pm<-f_x, -f_y, 1>dxdy
$$

## Parametric surfaces

Nếu tất cả các biến phụ thuộc vào tham số, ví dụ như:

$$
\begin{cases}
x = x(u, v) \\ 
y = y(u, v) \\ 
z = z(u, v) \\ 
<x, y, z> = \vec r = r(u, v) \\ 
\end{cases}
$$

Thế thì ta có thể tính thông lượng sử dụng hai biến u và v. Ta có:

$$
\frac {\partial \vec r}{\partial u}\Delta u = 
\left<\frac{\partial x}{\partial u}\Delta x,
\frac{\partial y}{\partial u}\Delta y,
\frac{\partial z}{\partial u}\Delta z
\right> 
$$

$$
\frac {\partial \vec r}{\partial v}\Delta v = 
\left<\frac{\partial x}{\partial v}\Delta x,
\frac{\partial y}{\partial v}\Delta y,
\frac{\partial z}{\partial v}\Delta z
\right> 
$$

$$
\Delta S = \left(\frac{\partial \vec r}{\partial u}\Delta u \right) \times \left(\frac{\partial \vec r}{\partial v}\Delta v \right) = 
\left(\frac{\partial \vec r}{\partial u} \times \frac{\partial \vec r}{\partial v} \right)\Delta x \Delta y
$$

Cuối cùng:

$$
d\vec S = \left(\frac{\partial \vec r}{\partial u} \times \frac{\partial \vec r}{\partial v} \right)dxdy
$$

## Implicit surfaces
Nếu ta có:

1) $ax + by + cz = d$ $\longrightarrow \vec N = <a, b, c>$
2) Mặt phẳng g(x, y, z) = 0 $\longrightarrow \vec N = \nabla g$

$$
\hat n dS = \pm \frac {|\vec N|}{|\vec N \cdot \hat k|}dxdy
$$

___
# Divergence theorem - Gauss-Green theorem

Cho:

* $V$ là một khối trong không gian
* $S = \partial V$ là mặt kín bao quanh $V$
* $F = (P, Q, R)$ là trường vector

Khi đó:

$$
\iint_S \mathbf F \cdot \hat n dS = \iiint_V \nabla \cdot \mathbf F dV
$$

trong đó:

* $\hat n$ là vector pháp tuyến đơn vị hướng ra ngoài.
* $\nabla \cdot \mathbf F$ là divergence của trường vector, $div(<P, Q, R>) = P_x + Q_y + R_z$.

## Ý nghĩa hình học
**LHS:**
$$
\iint_S \mathbf F \cdot \hat n dS
$$

là tổng lượng trường đi xuyên qua mặt kín.

**RHS:**
$$
\iiint \nabla \cdot \mathbf F dV
$$

là tổng nguồn phát sinh bên trong khối.

Nếu divergence dương $\longrightarrow$ trường được tạo ra bên trong.

Nếu divergence âm $\longrightarrow$ trường được hút vào bên trong.

___
# Del notation

$$
\nabla = \left<\frac{\partial}{\partial x}, \frac{\partial}{\partial y}, \frac{\partial}{\partial z} \right>
$$

**Ví dụ:**

- Gradient: $\nabla f$
$$
\nabla f = \left<\frac{\partial f}{\partial x}, \frac{\partial f}{\partial y}, \frac{\partial f}{\partial z} \right>
$$

- Divergence: $\nabla \cdot \mathbf F$

$$
\nabla \cdot \mathbf F= \left<\frac{\partial}{\partial x}P, \frac{\partial}{\partial y}Q, \frac{\partial}{\partial z} R\right> = P_x + Q_y + R_z
$$

## Physical interpretation

___
# Proof of Gauss-Green thm.

## Bước 1: Tách cách thành phần và chứng minh

Ta cần chứng minh:

$$
\iint_C \mathbf F \cdot d\vec S = \iiint_D \nabla \cdot \mathbf F dV
$$

với $\mathbf F = <P, Q, R>$. Do:

$$
\nabla \cdot \mathbf F = P_x + Q_y + R_z
$$ 

nên

$$
\iiint_D (P_x + Q_y + R_z)dV = 
\iiint_D P_x dV + 
\iiint_D Q_y dV + 
\iiint_D R_z dV 
$$

$$
\iint_S \mathbf F \cdot d\vec S = 
\iint_S PdS_x + 
\iint_S QdS_y + 
\iint_S RdS_z
$$

Vì các thành phần độc lập với nhau, vì vậy chỉ cần chứng minh:

$$
\iint_S R\hat k \cdot d\vec S = \iiint_D R_z dV
$$

và tương tự với $\iint_S P\hat i \cdot d\vec S, \iint_SQ\hat j\cdot d\vec S$.

## Bước 2: Miền đơn giản theo phương z

Giả sử miền $D = \{(x, y, z) : (x, y) \in \mathbb U, z_1(x, y) \leq x \leq z_2(x, y)\}$.

Tức là miền bị kẹp giữa hai mặt:

* Bottom: $z = z_1(x, y)$
* Top: $z = z_2(x, y)$

## Bước 3: Tính tích phân thể tích

Ta có $\iiint_D R_zdV$, do miền đơn giản theo z, nên thành:

$$
\iint_U \left(\int_{z_1}^{z_2}R_zdz \right)dxdy
$$

Áp dụng fundamental theorem of calculus $\int_{z_1}^{z_2}R_zdz = R(x, y, z_2) - R(x, y, z_1)$, nên:

$$
\iiint_D R_zdV = \iint_U(R(x, y, z_2) - R(x, y, z_1))dxdy
$$

## Bước 4: Flux through top

Ta có mặt trên $z = z_2(x, y)$, tham số hóa ta được:

$$
\mathbf r(x, y) = (x, y, z_2(x, y))
$$

Có hai vector tiếp tuyến:

$$
\mathbf r_x = (1, 0, z_{2x}) \qquad \mathbf r_y = (0, 1, z_{2y})
$$

tích có hướng: 

$$
\mathbf r_x \times \mathbf r_y = <-z_{2x}, -z_{2y}, 1>
$$

Vậy:

$$
d\vec S = \left<-\frac{\partial z_2}{\partial x}, -\frac{\partial z_2}{\partial y}, 1\right>dxdy 
$$

tích vô hướng:

$$
R\hat k \cdot d\vec S = <0, 0, R>\cdot<-z_{2x}, -z_{2y}, 1> = R
$$

do đó:

$$
\iint_{top}R\hat k \cdot d\vec S = \iint_U R(x, y, z_2)dxdy
$$

## Bước 5: Flux through bottom

Tương tự nhưng mà tiếp tuyến đổi hướng, vậy nên:

$$
d\vec S = \left<\frac{\partial z_1}{\partial x}, \frac{\partial z_1}{\partial y}, -1\right>dxdy 
$$

Vậy:

$$
\iint_{bottom}R\hat k \cdot d\vec S = -\iint_U R(x, y, z_1)dxdy
$$

## Bước 6: Flux through sides

Các pháp tuyến nằm ngang, và các mặt phẳng nằm dựng đứng, vậy nên thông lượng qua các mặt = 0.

## Bước 7: Tổng kết

Thông lượng toàn bộ mặt:

$$
\iint_S R\hat k \cdot d\vec S = 
\iint_U R(x, y, z_2)dxdy - 
\iint_U R(x, y, z_1)dxdy
$$

Hay tóm gọn lại:

$$
\iint_S R\hat k \cdot d\vec S = 
\iint_U (R(x, y, z_2) - R(x, y, z_1))dxdy 
$$

Mà ở bước 3, ta tính được:

$$
\iiint_D R_zdV = \iint_U(R(x, y, z_2) - R(x, y, z_1))dxdy
$$

Vậy:

$$
\iint_S R\hat k \cdot d\vec S = \iiint_D R_zdV
$$

___
# Laplacian

Toán tử Laplace là một toán tử vi phân bậc hai trong giải tích vectơ, được định nghĩa là độ phân kỳ của đạo hàm bậc nhất của một hàm vô hướng.

Ký hiệu là: $\nabla^2$ hoặc $\Delta$.

* $\nabla \cdot \nabla \mathbf F = \nabla^2 \mathbf F = \Delta \mathbf F$
* 2D: $\frac{\partial^2f}{\partial x^2} + \frac{\partial^2f}{\partial y^2}$
* 3D: $\frac{\partial^2f}{\partial x^2} + \frac{\partial^2f}{\partial y^2} + \frac{\partial^2f}{\partial z^2}$

## Ý nghĩa của Laplacian
Laplacian đo xem giá trị tại một điểm cao hơn hay thấp hơn trung bình các điểm lân cận.

Nếu 
$$
\nabla^2f>0
$$
thì điểm đó thấp hơn vùng xung quanh $\Rightarrow$ chất hoặc nhiệt sẽ chảy vào $\Rightarrow$ u tăng.

Nếu 
$$
\nabla^2f<0
$$
thì điểm đó cao hơn vùng xung quanh $\Rightarrow$ chất hoặc nhiệt sẽ chảy ra $\Rightarrow$ u giảm.

Do đo phương trình khuếch tán luôn có xu hướng làm trung bình hóa phân bố theo thời gian.

___
# Applications of Gauss-Green thm.

## Diffusion equation
Phương trình khuếch tán ví dụ như quản lý chuyển động của khói trong không khí (đứng yên), màu thuốc nhuộm trong dung dịch, ...

Phương trình là:

$$
\frac{\partial u}{\partial t} = k\nabla^2u 
= k \left(\frac{\partial^2u}{\partial x^2} + 
\frac{\partial^2u}{\partial y^2} +
\frac{\partial^2u}{\partial z^2} \right)
$$

Trong đó:

* $u = (x, y, z, t)$ là đại lượng khuếch tán tại $x, y, z$ vào thời điểm $t$.
* $k$ là hệ số khuếch tán.
* $\nabla^2$ toán tử Laplacian.

Và **heat equation** là một trường hợp đặc biệt của **diffusion equation**.


___
# End
