---
title: "Đạo hàm đa biến"
---

___
# 1. Vector và ma trận - Vectors and Matrices
* **1.1.** Vectors
* **1.2.** Dot product
* **1.3.** Determinants
* **1.4.** Cross product
* **1.5.** Matrices
* **1.6.** Square systems; Equation of planes
* **1.7.** Parametric equations for lines and curves
* **1.8.** Velocity 
* **1.9.** Acceleration
* **1.10.** Kepler's Second law

___
# 2. Đạo hàm riêng - Partial derivatives
* **2.1.** Functions of several variables - *Hàm nhiều biến*
    * **2.1.1.** Contour plot - *Đồ thị đường bao*
* **2.2.** Parital derivatives - *Đạo hàm riêng*
* **2.3.** Tangent plane approx - *Mặt phẳng tiếp tuyến*
    * **2.3.1.** Appox formula - *Công thức xấp xỉ*
    * **2.3.2.** Tangent plane - *Mặt phẳng tiếp tuyến*
* **2.4.** Max - Min problems - *Bài toán cực trị*
    * **2.4.1.** Max point - *Điểm cực đại*
    * **2.4.2.** Min point - *Điểm cực tiểu*
    * **2.4.3.** Saddle point - *Điểm yên ngựa*
* **2.5.** Least squares - *Bài toán tối ưu*
* **2.6.** Second derivative - *Đạo hàm bậc hai*
* **2.7.** Differentials; Chain rule
    * **2.7.1.** Total differential - *Đạo hàm toàn phần*
    * **2.7.2.** Chain rule - *Quy tắc chuỗi*
    * **2.7.3.** Application - *Ứng dụng*
* **2.8.** Gradient - *Gradient*
* **2.9.** Direction derivative - *Đạo hàm theo hướng*
* **2.10.** Lagrange multipliers - *Nhân tử Lagrange*
* **2.11.** Non-independent variables - *Các biến phụ thuộc*

___
# 3. Tích phân kép và tích phân đường trong mặt phẳng - Double integrals and Line integrals in the plane
* **3.1.** Double integral
    * **3.1.1.** Calculation
    * **3.1.2.** Change the order
* **3.2.** Integration in Polar coordinates
* **3.3.** Change of variables
    * **3.3.1.** Change of variables 
    * **3.3.2.** Jacobians
    * **3.3.3.** Calculation upperr and lower limit
* **3.4.** Vector fields
* **3.5.** Line integrals
    * **3.5.1.** Work
    * **3.5.2.** Calculation Line integrals
* **3.6.** Path independence
    * **3.6.1.** Fundamental theorem of calculus for line integral
    * **3.6.2.** Path independence
* **3.7.** Conservative fields
* **3.8.** Test for Gradient fields
* **3.9.** Finding the Potential function
    * **3.9.1.** Method 1: Using Line integral
    * **3.9.2.** Method 2: Using Antiderivatives
* **3.10.** Curl
    * **3.10.1.** Why $N_x - M_y$?
    * **3.10.2.** Interpretation Curl
* **3.11** Green's Theorem
    * **3.11.1.** Calculation
    * **3.11.2.** Application
    * **3.11.3.** Proof
* **3.12.** Flux
    * **3.12.1.** Divergence
    * **3.12.2.** Green's theorem for flux
* **3.13.** Simply connected regions 



___
# 4. Tích phân bội ba và tích phân mặt trong không gian ba chiều - Triple integrals and Surface integrals in the 3-space
* **4.1** Triple integrals in rectangular and cylindrical coordinates
* **4.2** Spherical coordinates; Surface area 
* **4.3** Vector fields in 3D; Surface integrals and flux
* **4.4** Divergence theorem
* **4.5** Divergence theorem and its Applications and Proof
* **4.6** Line integrals in space, Curl, Exactness and potentials
* **4.7** Stokes's theorem
* **4.8** Topological considerations
* **4.9** Maxwell's equations