---
title: "Đại số tuyến tính"
---

Đây chỉ là bản copy rẻ tiền và không đầy đủ của [daisotuyentinh.com](https://www.daisotuyentinh.com/) được viết bởi thầy Phạm Đình Đồng, cô Trần Nguyễn Khánh Linh, thầy Lê Ngọc Long và thầy Huỳnh Đình Tuân, giảng viên Khoa Toán học, Trường ĐHSP - Đại học Huế. 

<!-- Bằng một số thông hiểu của tôi, tôi sẽ giải thích nó bằng hình học (vì hình học là môn tôi ghét nhất trong cấp 3 (đặc biệt là Vector (nhưng may mắn làm sao, đại số tuyến tính lại gắn liền với Vector))).


Các tài liệu mà tôi tham khảo:


- [daisotuyentinh](https://www.daisotuyentinh.com/)
- [Linear Algebra - Gilbert Strang](https://rksmvv.ac.in/wp-content/uploads/2021/04/Gilbert_Strang_Linear_Algebra_and_Its_Applicatio_230928_225121.pdf)
- [Essence of linear algebra - 3blue1brown](https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab)


Về ưu và nhược điểm, có thể nói vui vẻ như sau:

- **Daisotuyentinh.com**: đơn giản, dễ hiểu, viết bằng Tiếng Việt, có các chứng minh, nhưng khó hiểu.
- **Linear Gilbert của thầy Gilbert Strang**: tài liệu của MIT, viết bằng Tiếng Anh, sẽ rất khó hiểu vì nó sẽ chứng minh một cách từ từ, nhưng nó sẽ kiểu như là gợi ý cách mình suy nghĩ là nhiều hơn, thêm một ưu điểm nữa là nó sẽ phù hợp hơn với những người thích suy nghĩ (còn tôi thì không).
- **Essence of Linear Algebra của 3xanhdương1nâu**: cực kỳ dị, sẽ không theo bất kỳ roadmap nào thường được thấy trong sách, nó sẽ chứng minh bằng hình học nhiều hơn (thật ra là 100% hình học), cực kỳ trực quan và dễ hiểu.  -->

# Chương I. Tiền đề

* Tập hợp 

* Ánh xạ

* Vành và trường số

# Chương II. Ma trận và Hệ phương trình tuyến tính

* Giới thiệu về hệ phương trình tuyến tính

* Ma trận

* Phương pháp khử Gauss - Jordan

* Biện luận hệ phương trình và ứng dụng

* Các phép toán trên ma trận

* Ma trận khả nghịch và các tính chất

# Chương III. Không gian Vector

* Khái niệm về không gian Vector

* Hệ Vector độc lập tuyến tính

* Cơ sở và chiều của không gian Vector

* Tọa độ và ma trận chuyển cơ sở

* Tổng và tổng trực tiếp

# Chương IV. Ánh xạ tuyến tính

* Ánh xạ tuyến tính

* Ma trận của ánh xạ tuyến tính

* Ảnh và hạt nhân của đồng cấu

* Không gian Vector đối ngẫu

# Chương V. Định thức và ứng dụng

* Định thức của ma trận

* Khai triển định thức

* Các ứng dụng của định thức

# Chương VI. Giá trị riêng và bài toán chéo hóa

* Không gian con bất biến

* Đa thức đặc trưng

* Bài toán chéo hóa và ứng dụng

